name: BetterSkulls
version: '${version}'
main: de.raphaelgoetz.betterskulls.BetterSkulls
api-version: '1.20'
description: A simple plugin to get some skulls
author: Konfuzius
website: https://uroria.com

commands:
  skull:
    description: Open
  skullsearch:
    description: Openm