name: BetterSkulls
version: '${version}'
main: de.raphaelgoetz.betterskulls.BetterSkulls
api-version: '1.20'
description: A simple plugin to get some skulls
author: Konfuzius
website: https://uroria.com

commands:
  skull:
    description: Opens an overview of all categories.
  skullsearch:
    description: Opens an inventory of the requested skulls.
  getskull:
    description: Gets a skull of the requested player's name.